# Generated by Django 3.2.3 on 2021-05-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Категория')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='День создания')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='День modified')),
                ('status', models.CharField(choices=[('АКТИВНО', 'Активно'), ('НЕ АКТИВНО', 'Не активно')], max_length=10, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(auto_created=True, verbose_name='Дедлайн')),
                ('title', models.CharField(max_length=255, verbose_name='Задание')),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='День создания')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='День modified')),
                ('status', models.CharField(choices=[('ЗЕЛЁНЫЙ', 'Зелёный'), ('ЖЕЛТЫЙ', 'Желтый'), ('КРАСНЫЙ', 'Красный')], max_length=9, verbose_name='Статус')),
                ('done', models.BooleanField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.category', verbose_name='Категория')),
            ],
        ),
    ]
