# Generated by Django 3.2.3 on 2021-05-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210518_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ЗЕЛЕНЫЙ', 'Зеленый'), ('ЖЕЛТЫЙ', 'Желтый'), ('КРАСНЫЙ', 'Красный')], max_length=9, verbose_name='Статус'),
        ),
    ]
